name: CI

on:
  push:
  pull_request:
    branches: [ $default-branch ]
  release:
    types:
      - created

jobs:
  test:
    name: "Erlang Test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [25, 26, 27]
      fail-fast: false
    container:
      image: erlang:${{ matrix.otp }}
    steps:
    - uses: actions/checkout@v3

    - name: Mark Git directory as safe
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Run CI
      shell: bash
      run: make ci
